server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health"
    access:
      default: read_only
  endpoint:
    health:
      access: read_only

spring:
  application:
    name: SyncTexNg-RMQ-Server

  rabbitmq:
    listener:
      direct:
        auto-startup: false
      simple:
        auto-startup: false
