server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health"
    access:
      default: read_only
  endpoint:
    health:
      access: read_only

spring:
  application:
    name: SyncTexNg-RMQ-Server

  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:guest}
    password: ${RMQ_PASSWORD:guest}
    virtual-host: ${RMQ_VHOST:/}

synctexng:
    server:
      queue-tex-requests: ${RMQ_QUEUE_TEX_REQUESTS:tex-requests}
